### ISSUE TITLE
Function modifies the state but is marked "constant"

### ISSUE THREAD

**Issue by shoenseiwaso** [brickblock-io/smart-contract-structure#3]
This modifies the state by instantiating a new contract and adding it to the list of POA tokens. Don't think it should be marked constant?

Also, are you sure you want to allow anyone to be able to call this function?

https://github.com/brickblock-io/smart-contract-structure/blob/76351a4148c1c24b9394666d194a6859ed9b336b/contracts/Brickblock.sol#L71

**Comment by TovarishFin** [comment]
This is very old example code and there will be an update probably within in the next few weeks. This amongst many other issues are resolved in upcoming updates. Thanks for pointing it out regardless :)

The only contract that is up for audit currently is BrickblockToken.
